#! /bin/sh

if [ -z "$USER" ]; then
    USER=$(id -un)
fi

echo >&2 "====================================================================="
echo >&2 " Setting up codespaces environment"
echo >&2 ""
echo >&2 " USER        $USER"
echo >&2 " HOME        $HOME"
echo >&2 "====================================================================="

cd $HOME

export SUDO_ASKPASS=/bin/true

rm -rf .oh-my-bash
rm -rf .oh-my-zsh
rm .zshrc

mv .gitconfig .gitconfig.private
git clone https://github.com/ericboehs/dotfiles .dotfiles.base

# Prep for apt-get installs
sudo apt-get update -qq

# Install zsh
sudo apt-get install -y zsh
sudo chsh -s /usr/bin/zsh $USER

mkdir $HOME/bin

# Install development tools
sudo apt-get -y install stow xclip tmux

# Install fzf
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install --all
cd $HOME

# Install zsh-quickstart-kit
rm ~/.zshrc
git clone https://github.com/jandamm/zgenom.git
git clone https://github.com/unixorn/zsh-quickstart-kit.git .zsh-quickstart-kit
cd $HOME/.zsh-quickstart-kit
stow --target=$HOME zsh
cp /workspaces/.codespaces/.persistedshare/dotfiles/.p10k.zsh $HOME
zqs disable-ssh-key-listing
zqs disable-ssh-key-loading

# Install neovim
NVIM_VERSION=0.9.5
cd $HOME/bin
wget https://github.com/neovim/neovim/releases/download/v${NVIM_VERSION}/nvim-linux64.tar.gz
tar xzf nvim-linux64.tar.gz
ln -s $HOME/bin/nvim-linux64/bin/nvim $HOME/bin/nvim
cd $HOME

# Install tpm & catpuccin
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
cat <<'EOF' > ~/.tmux.conf
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'

# Configure tmux
set -g @catppuccin_window_icons_enabled on
set -g @catppuccin_flavour 'mocha'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
EOF
~/.tmux/plugins/tpm/bin/install_plugins

# Install nvchad
sudo apt-get install -y ripgrep
git clone https://github.com/NvChad/starter ~/.config/nvim
nvim &
pid=$!
sleep 25; kill $pid
