#! /bin/sh

if [ -z "$USER" ]; then
    USER=$(id -un)
fi

echo >&2 "====================================================================="
echo >&2 " Setting up codespaces environment"
echo >&2 ""
echo >&2 " USER        $USER"
echo >&2 " HOME        $HOME"
echo >&2 "====================================================================="

cd $HOME

export SUDO_ASKPASS=/bin/true

rm -rf .oh-my-bash
rm -rf .oh-my-zsh
rm .zshrc

mv .gitconfig .gitconfig.private
git clone https://github.com/ericboehs/dotfiles .dotfiles.base

# Install zsh
sudo-apt-get update
sudo apt-get install -y zsh
sudo chsh -s /usr/bin/zsh $USER

mkdir $HOME/bin

# Install fzf
FZF_VERSION=0.48.1
curl -L https://github.com/junegunn/fzf/releases/download/${FZF_VERSION}/fzf-${FZF_VERSION}-linux_amd64.tar.gz | tar xzC $HOME/bin

# Install neovim
NVIM_VERSION=0.9.5
pushd $HOME/bin
wget https://github.com/neovim/neovim/releases/download/v${NVIM_VERSION}/nvim-linux64.tar.gz
tar xzvf nvim-linux64.tar.gz
ln -s $HOME/bin/nvim-linux64/bin/nvim $HOME/bin/nvim
popd
